### ISSUE TITLE
Should we remove nim_viosupgrade.py?

### ISSUE THREAD

**Issue by dberg1** [ansible-aix/ansible-power-aix#17]
This was implemented using viosupgrade script before nim_upgradeios was added.
Is it still relevant?

**Comment by robinvy** [comment]
**nim_viosupgrade** uses the /usr/sbin/viosupgrade command running on a VIOS itself (some TODOs remain in the module + tests).

**nim_upgradeios** uses the NIM actions to upgrade each target VIOS from the NIM master (still some TODOs remain in the module)
It allows to create/view/restore a backup of the VIOS configuration and to upgrade and restore a VIOS.

We should keep both modules.
Later (2021) nim_viosupgrade should be updated and modified to run locally on the VIOS or remotely through the NIM master.
