### ISSUE TITLE
Review vios-health-checker ?

### ISSUE THREAD

**Issue by robinvy** [ansible-aix/ansible-power-aix#24]
Check if we should re-work on the vios-health-checker.
https://github.com/aixoss/vios-health-checker

What can be improved , (use run_command instead of exec_cmd etc.)
How will it be supported by IBM?
Do we keep the aixoss repository?
Is this issue part of the project or is it a side work item?

**Comment by robinvy** [comment]
Damien tested vSCSI and NPIv, seems to work correctly.
Still need to check vNIC? maybe later.

**Comment by dberg1** [comment]
Also tested SEA.
SSP not tested but since it uses VSCSI mappings, it should be fine with current code.

**Comment by dberg1** [comment]
Also need to create an Ansible role to install the vioshc script on victims and drop the vioshc.py script in our git repo under this role.
