### ISSUE TITLE
Create user login for Ansible Tower

### ISSUE THREAD

**Issue by robinvy** [ansible-aix/ansible-power-aix#3]
Create (team) user login for Ansible Tower

**Comment by pbfinley1911** [comment]
New (group) member login has been added to Ansible Tower.  This environment is being used by several teams, so let's discuss some common practices in our upcoming meetings.

[Ansible Tower](https://ansible-demos.aus.stglabs.ibm.com/#/login)

login ID:     aix-dev
password: passw0rd
